name: multijob

on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1-step
        run: echo "I'm job1"
        
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: job2-step
        run: echo "I'm job2"
