name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "First workflow successfully executed."
      - name: Multiline Command
        run: |

          
          echo "Test command 1"
          echo "Test command 2"
